services:
  borg-ui:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "52134:52134"
    command: sh -c "yarn install && yarn dev --host 0.0.0.0 --port 52134" 