services:
  borg-ui:
    build: .
    container_name: borg-ui

    # internal Caddy listens on 2015
    expose:
      - "2015"

    networks:
      - caddy

    labels:
      # caddy-docker-proxy will pick up this service
      caddy: ui.unimatrix-01.dev
      caddy.reverse_proxy: "borg-ui:2015"
      caddy.encode: gzip
      caddy.header.Cache-Control: "public, max-age=604800"

    restart: unless-stopped

networks:
  caddy:
    external: true
